<?php $element->setAttribute('class', 'form-control ' . $element->getAttribute('class')); ?>

<div class="form-group <?php if($form->hasErrorElement($element)): ?>has-error<?php endif; ?>">
    <?= $this->formLabel($element) ?>
    <?= $this->formElement($element) ?>
    <?= $this->formElementErrors()
        ->setMessageOpenFormat('<span class="help-block">')
        ->setMessageSeparatorString(', ')
        ->setMessageCloseString('</span>')
        ->render($element, ['class' => 'help-block']) ?>
</div>
