<?php echo $this->doctype() ?>
<html>
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->layoutLte()->title)->setTranslatorEnabled(false)->setSeparator(' - ')->setAutoEscape(false) ?>
        
        <?php echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        
        <?php echo $this->headLink()
                ->prependStylesheet($this->basePath('mia-layout-lte/plugins/iCheck/flat/blue.css'))
                ->prependStylesheet($this->basePath('mia-layout-lte/dist/css/AdminLTE.min.css'))
                ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css')
                ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath('mia-layout-lte/bootstrap/css/bootstrap.min.css'));
                //$this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ?>

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body class="hold-transition login-page">
        <div class="login-box">
            <div class="login-logo">
                <a href="#"><b><?php echo $this->layoutLte()->titlePartOne; ?></b><?php echo $this->layoutLte()->titlePartTwo; ?></a>
            </div>
            <!-- /.login-logo -->
            <div class="login-box-body">
                <p class="login-box-msg">Inicia sesión para poder ingresar:</p>

                <?php echo $this->form()->openTag($form); ?>
                    <?php $email = $this->form->get('email'); ?>
                    <div class="form-group has-feedback">
                        <input type="email" class="form-control" name="<?php echo $email->getName(); ?>" placeholder="<?php echo $email->getOption('label'); ?>">
                        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                    </div>
                    <?php $password = $this->form->get('password'); ?>
                    <div class="form-group has-feedback">
                        <input type="password" class="form-control" name="<?php echo $password->getName(); ?>" placeholder="<?php echo $password->getOption('label'); ?>">
                        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                    </div>
                    <div class="row">
                        <div class="col-xs-8">
                            <?php $rememberMe = $this->form->get('remember_me'); ?>
                            <div class="checkbox">
                                <label>
                                    <input name="<?php echo $rememberMe->getName(); ?>" type="checkbox" value="1"> <?php echo $rememberMe->getOption('label'); ?>
                                </label>
                            </div>
                        </div>
                        <!-- /.col -->
                        <div class="col-xs-4">
                            <button type="submit" class="btn btn-primary btn-block btn-flat">Ingresar</button>
                        </div>
                        <!-- /.col -->
                    </div>
                <?php echo $this->form()->closeTag(); ?>

                <!--<div class="social-auth-links text-center">
                    <p>- OR -</p>
                    <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign in using
                        Facebook</a>
                    <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign in using
                        Google+</a>
                </div>

                <a href="#">I forgot my password</a><br>
                <a href="register.html" class="text-center">Register a new membership</a>-->

            </div>
            <!-- /.login-box-body -->
        </div>
        <!-- /.login-box -->

        
        <!-- Scripts -->
        <?php echo $this->headScript()
                ->prependFile($this->basePath('mia-layout-lte/plugins/iCheck/icheck.min.js'))
                ->prependFile($this->basePath('mia-layout-lte/bootstrap/js/bootstrap.min.js'))
                ->prependFile($this->basePath('mia-layout-lte/plugins/jQuery/jquery-2.2.3.min.js'))
        ?>
        
        <?php echo $this->inlineScript() ?>

        <script>
            $(function () {
                $('.icheck').iCheck({
                    checkboxClass: 'icheckbox_square-blue',
                    radioClass: 'iradio_square-blue',
                    increaseArea: '20%' // optional
                });
            });
        </script>
    </body>
</html>

