<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Simple Form
            <small>preview of simple tables</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Tables</a></li>
            <li class="active">Simple</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- /.row -->
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title">Responsive Hover Form</h3>
                    </div>
                    <!-- /.box-header -->
                    <?php echo $this->form()->openTag($form); ?>
                        <div class="box-body">
                            <?php foreach($form->getElements() as $element): ?>
                                <?php include('element/' . $form->getElementType($element) . '.phtml'); ?>
                            <?php endforeach; ?>
                        </div>
                        <!-- /.box-body -->
                    <?php echo $this->form()->closeTag(); ?>
                </div>
                <!-- /.box -->
            </div>
        </div>
    </section>
    <!-- /.content -->
</div>

