<?php $this->headTitle($this->string['title_page']); ?>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            <?php echo $this->string['main_title_add']; ?>
            <small><?php echo $this->string['main_caption_add']; ?></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Tables</a></li>
            <li class="active">Simple</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- /.row -->
        <div class="row">
            <div class="col-xs-8">
                <div class="box box-primary">
                    <!--<div class="box-header">
                        <h3 class="box-title">Responsive Hover Form</h3>
                    </div>-->
                    <!-- /.box-header -->
                    <?php echo $this->lteForm($form); ?>
                </div>
                <!-- /.box -->
            </div>
            <div class="col-xs-4">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title">Preview</h3>
                    </div>
                    <?php echo $this->partial($this->template_preview); ?>
                </div>
                <!-- /.box -->
            </div>
        </div>
    </section>
    <!-- /.content -->
</div>

<script type="text/javascript">
<?php $this->headScript()->captureStart() ?>
    // Buscar si hay campos con errores
    $('.has-error').each(function(index, element){
        if(index == 0){
            setTimeout(function() {
                $(element).find('.form-control').focus();
            }, 0);
        }
        var helpBlock = $(element).find('.help-block');
        if(helpBlock.text() == "Value is required and can't be empty"){
           helpBlock.text("Este campo es necesario!"); 
        }
    });
<?php $this->headScript()->captureEnd() ?>
</script>