<?php $this->headTitle($this->string['title_page']); ?>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            <?php echo $this->string['main_title']; ?>
            <small><?php echo $this->string['main_caption']; ?></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Tables</a></li>
            <li class="active">Simple</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- /.row -->
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title"><?php echo $this->string['title']; ?></h3>

                        <?php if($service->getOption('has_search', false)): ?>
                        <div class="box-tools">
                            <form action="" method="get">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="q" id="list-query-search" class="form-control pull-right" placeholder="Search">

                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                            </form>
                        </div>
                        <?php endif; ?>
                    </div>
                    <?php if($service->getOption('allow_add', true)): ?>
                    <div class="box-header">
                        <?php if($this->is_relation === true): ?>
                        <a href="<?php echo $this->url($this->route . '/add', array('id' => $relation_value)); ?>">Agregar</a>
                        <?php else: ?>
                        <a href="<?php echo $this->url($this->route . '/add'); ?>">Agregar</a>
                        <?php endif; ?>
                    </div>
                    <?php endif; ?>
                    <!-- /.box-header -->
                    <div class="box-body table-responsive no-padding">
                        <table class="table table-hover">
                            <tr>
                                <?php foreach($service->getOption('columns', array()) as $column): ?>
                                <th><?php echo $column['title']; ?></th>
                                <?php endforeach; ?>
                            </tr>
                            <?php foreach($this->paginator as $item): ?>
                            <tr>
                                <?php foreach($service->getOption('columns', array()) as $column): ?>
                                <?php include('column/' . $column['type'] . '.phtml'); ?>
                                <?php endforeach; ?>
                            </tr>
                            <?php endforeach; ?>
                        </table>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer clearfix">
                        <?= $this->paginationControl($this->paginator, 'Sliding', 'mia-layout-lte/paginator/search') ?>
                    </div>
                </div>
                <!-- /.box -->
            </div>
        </div>
    </section>
    <!-- /.content -->
</div>
