<?= $this->doctype() ?>
<html>
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setTranslatorEnabled(false)->setSeparator(' - ')->setAutoEscape(false) ?>

        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?=
                //$this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                $this->headLink()
                ->prependStylesheet($this->basePath('mia-layout-lte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css'))
                ->prependStylesheet($this->basePath('mia-layout-lte/plugins/daterangepicker/daterangepicker.css'))
                ->prependStylesheet($this->basePath('mia-layout-lte/plugins/datepicker/datepicker3.css'))
                ->prependStylesheet($this->basePath('mia-layout-lte/plugins/jvectormap/jquery-jvectormap-1.2.2.css'))
                ->prependStylesheet($this->basePath('mia-layout-lte/plugins/morris/morris.css'))
                ->prependStylesheet($this->basePath('mia-layout-lte/plugins/iCheck/flat/blue.css'))
                ->prependStylesheet($this->basePath('mia-layout-lte/dist/css/skins/_all-skins.min.css'))
                ->prependStylesheet($this->basePath('mia-layout-lte/dist/css/AdminLTE.min.css'))
                ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css')
                ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath('mia-layout-lte/bootstrap/css/bootstrap.min.css'))
        ?>

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body class="hold-transition skin-blue sidebar-mini">
        <div class="wrapper">

            <header class="main-header">
                <!-- Logo -->
                <a href="#" class="logo">
                    <!-- mini logo for sidebar mini 50x50 pixels -->
                    <span class="logo-mini"><b>A</b>LT</span>
                    <!-- logo for regular state and mobile devices -->
                    <span class="logo-lg"><b>Admin</b>LTE</span>
                </a>
                <!-- Header Navbar: style can be found in header.less -->
                <nav class="navbar navbar-static-top">
                    <!-- Sidebar toggle button-->
                    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                        <span class="sr-only">Toggle navigation</span>
                    </a>

                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            <?php include('user-menu.phtml'); ?>
                        </ul>
                    </div>
                </nav>
            </header>
            <!-- Left side column. contains the logo and sidebar -->
            <aside class="main-sidebar">
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar">
                    <!-- sidebar menu: : style can be found in sidebar.less -->
                    <?php $this->navigation()->menu()->setPartial('mia-layout-lte/menu/basic'); ?>
                    <?php echo $this->navigation('Zend\Navigation\Backend')->menu() ?>
                </section>
                <!-- /.sidebar -->
            </aside>

            <!-- Content Wrapper. Contains page content -->
            <?= $this->content ?>
            <!-- /.content-wrapper -->
            
            <?php include('footer.phtml'); ?>

            <!-- Add the sidebar's background. This div must be placed immediately after the control sidebar -->
            <div class="control-sidebar-bg"></div>
        </div>
        <!-- ./wrapper -->

        <!-- Scripts -->
        <?=
                $this->headScript()
                ->prependFile($this->basePath('mia-layout-lte/dist/js/demo.js'))
                ->prependFile($this->basePath('mia-layout-lte/dist/js/pages/dashboard.js'))
                ->prependFile($this->basePath('mia-layout-lte/dist/js/app.min.js'))
                ->prependFile($this->basePath('mia-layout-lte/plugins/fastclick/fastclick.js'))
                ->prependFile($this->basePath('mia-layout-lte/plugins/slimScroll/jquery.slimscroll.min.js'))
                ->prependFile($this->basePath('mia-layout-lte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js'))
                ->prependFile($this->basePath('mia-layout-lte/plugins/datepicker/bootstrap-datepicker.js'))
                ->prependFile($this->basePath('mia-layout-lte/plugins/daterangepicker/daterangepicker.js'))
                ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js')
                ->prependFile($this->basePath('mia-layout-lte/plugins/knob/jquery.knob.js'))
                ->prependFile($this->basePath('mia-layout-lte/plugins/jvectormap/jquery-jvectormap-world-mill-en.js'))
                ->prependFile($this->basePath('mia-layout-lte/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js'))
                ->prependFile($this->basePath('mia-layout-lte/plugins/sparkline/jquery.sparkline.min.js'))
                ->prependFile($this->basePath('mia-layout-lte/plugins/morris/morris.min.js'))
                ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js')
                ->prependFile($this->basePath('mia-layout-lte/bootstrap/js/bootstrap.min.js'))
                ->prependScript("$.widget.bridge('uibutton', $.ui.button);")
                ->prependFile('https://code.jquery.com/ui/1.11.4/jquery-ui.min.js')
                ->prependFile($this->basePath('mia-layout-lte/plugins/jQuery/jquery-2.2.3.min.js'))
        ?>
        
        <?= $this->inlineScript() ?>
    </body>
</html>